---
- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy website
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: '0644'

