---
- name: Launch a new EC2 instance
  amazon.aws.ec2_instance:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    image_id: "{{ ami_id }}"
    instance_type: "{{ instance_type }}"
    key_name: "{{ key_name }}"
    wait: yes
  register: ec2

- name: Debug EC2 output
  debug:
    var: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ ec2.instances[0].public_dns_name }}"
    groupname: launched

- name: Wait for SSH to come up
  wait_for:
    host: "{{ ec2.instances[0].public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started

