---
- name: Launch a new EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a new EC2 instance
      amazon.aws.ec2_instance:
        profile: my_aws_profile_name
        region: us-east-1
        instance_type: t2.micro
        image_id: ami-00beae93a2d981137
        count: 1
        wait: yes
        key_name: MYLABKEY
        vpc_subnet_id: subnet-8212e1c9
        security_group: ALL_TRAFFIC_ALLOWED
        network:
          assign_public_ip: yes
        tags:
          Name: MyNewInstance
      register: ec2

    - name: Debug EC2 instance details
      debug:
        var: ec2

    - name: Wait for the instance to be in running state
      amazon.aws.ec2_instance_info:
        instance_ids: "{{ ec2.instance_ids }}"
        region: us-east-1
        profile: my_aws_profile_name
      register: ec2_info
      until: ec2_info.instances[0].state.name == 'running'
      retries: 12
      delay: 10

    - name: Add the new instance to the host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: launched
      loop: "{{ ec2_info.instances }}"
      when: item.public_ip_address is defined

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip_address }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: "{{ ec2_info.instances }}"
      when: item.public_ip_address is defined

