- hosts: all
  become: true
  pre_tasks:

  - name: install updates (RedHat)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"
      

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: node03
  become: true
  tasks:

    # This play is for Ubuntu OS

  - name: install apache2 package
    apt:
      name: 
        - apache2
        - libapache2-mod-php  
      state: present
    when: ansible_distribution == "Ubuntu"


    # This play is for RHEL OS

  - name: install httpd package
    dnf:
      name: 
        - httpd
        - php
      state: present
    when: ansible_distribution == "RedHat"

- hosts: node02
  become: true
  tasks:

    - name: install mariadb package (Ubuntu)
      apt:
        name: mariadb
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install mariadb server (Redhat)
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "RehHat"
