# ansible_project/playbooks/playbook2.yml
---
- name: Start Nginx on web servers
  hosts: webservers
  become: true
  tasks:
    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started

