---
- name: Install Apache
  ansible.builtin.yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Nginx on Debian-based systems
  ansible.builtin.apt:
    name: nginx
    state: present
  when: ansible_os_family == "Debian"

- name: Start and enable Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Start and enable Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Deploy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  when: ansible_os_family == "RedHat"

- name: Deploy index.html for Nginx
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.nginx-debian.html
  when: ansible_os_family == "Debian"

