---
- name: Configure MySQL on database servers
  hosts: dbservers
  become: true
  tasks:
    - name: Ensure MySQL is installed
      yum:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started

