# ansible_project/playbooks/playbook1.yml
---
- name: Install Nginx on web servers
  hosts: webservers
  become: true
  tasks:
    - name: Ensure Nginx is installed
      yum:
        name: nginx
        state: present

