- name: Install Java on RedHat
  ansible.builtin.yum:
    name: java-1.8.0-openjdk
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Java on Debian/Ubuntu
  ansible.builtin.apt:
    name: openjdk-11-jdk
    state: present
  when: ansible_os_family == "Debian"

- name: Download Tomcat
  ansible.builtin.get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
    dest: /tmp/apache-tomcat-9.0.70.tar.gz

- name: Extract Tomcat
  ansible.builtin.unarchive:
    src: /tmp/apache-tomcat-9.0.70.tar.gz
    dest: /opt/
    remote_src: yes

- name: Create symbolic link for Tomcat
  ansible.builtin.file:
    src: /opt/apache-tomcat-9.0.70
    dest: /opt/tomcat
    state: link

- name: Set permissions
  ansible.builtin.file:
    path: /opt/tomcat
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Start Tomcat
  ansible.builtin.command: /opt/tomcat/bin/startup.sh

