---
- name: Install common packages on RedHat
  yum:
    name:
      - git
      - vim
      - curl
    state: present
  when: ansible_os_family == "RedHat"

- name: Install common packages on Debian/Ubuntu
  apt:
    name:
      - git
      - vim
      - curl
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

